application:
  meeting-radius: 300

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/connect_me_now
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      show-sql: true
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    io.connectmenow.connect: DEBUG
    org.hibernate: INFO

server:
  port: 8081